---
- name: openshift cni config
  set_fact:
    cni_config: "{{ openshift_cni_config }}"
  when: platform=="openshift"

- name: kubernetes cni config
  set_fact:
    cni_config: "{{ kubernetes_cni_config }}"
  when: platform=="kubernetes"

- name: Render multus deployment yaml
  template:
    src: multus.yml
    dest: /tmp/multus.yml

- name: Delete multus Resources
  command: kubectl delete -f /tmp/multus.yml --ignore-not-found

- name: Render cni plugins deployment yaml
  template:
    src: cni-plugins.yml
    dest: /tmp/cni-plugins.yml

- name: Delete cni plugins Resources
  command: kubectl delete -f /tmp/cni-plugins.yml --ignore-not-found

- name: Render OVS plugin deployment yaml
  template:
    src: ovs-cni.yml
    dest: /tmp/ovs-cni.yml

- name: Delete OVS plugin Resources
  command: kubectl delete -f /tmp/ovs-cni.yml --ignore-not-found

- name: Render ovs-vsctl deployment yaml
  template:
    src: ovs-vsctl.yml
    dest: /tmp/ovs-vsctl.yml

- name: Delete ovs-vsctl Resources
  command: kubectl delete -f /tmp/ovs-vsctl.yml --ignore-not-found
