---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Check that kubevirt.yaml still exists in /tmp
  stat:
    path: "/tmp/kubevirt.yaml"
  register: kubevirt_template

- name: Check for kubevirt.yml.j2 template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yaml.j2"
  register: byo_template
  when: kubevirt_template.stat.exists == False

- name: Download KubeVirt Template
  get_url:
    url: "{{ release_manifest_url }}/v{{ kubevirt_version }}/kubevirt.yaml.j2"
    dest: "{{ kubevirt_template_dir }}/kubevirt.yaml.j2"
  when: (kubevirt_template.stat.exists == False) and (byo_template.stat.exists == False)

- name: Render KubeVirt template
  template:
    src: "kubevirt.yaml.j2"
    dest: "/tmp/kubevirt.yaml"
  when: kubevirt_template.stat.exists == False

- name: Delete KubeVirt Resources
  command: kubectl delete -f /tmp/kubevirt.yaml --ignore-not-found=true

- name: Delete Privileged Policy
  command: "oc adm policy remove-scc-from-user privileged -z {{ item }} -n {{ namespace }}"
  with_items: "{{ kubevirt_privileged_policies | list }}"
  when: cluster=="openshift"

- name: Delete Hostmount-anyuid Policy
  command: "oc adm policy remove-scc-from-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"
