- name: Download KubeVirt Template
  get_url:
    url: "{{ kubevirt_manifest_url }}/{{ manifest_version }}/kubevirt.yaml.in"
    dest: "{{ kubevirt_template_dir }}/kubevirt.yml"
  when: byo_template.stat.exists == False

- name: Render KubeVirt Yml
  template:
    src: "{{ kubevirt_template_dir }}/kubevirt.yml"
    dest: /tmp/kubevirt.yml

- name: Remove downloaded templates
  file:
    path: "{{ kubevirt_template_dir }}/kubevirt.yml"
    state: absent
  when: byo_template.stat.exists == False
