kind: ServiceAccount
apiVersion: v1
metadata:
  name: cdi-sa
  namespace: {{ cdi_namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdi
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["cdi.io"]
  resources: ["datavolumes"]
  verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cdi-sa
roleRef:
  kind: ClusterRole
  name: cdi
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cdi-sa
    namespace: {{ cdi_namespace }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cdi-deployment
spec:
  selector:
    matchLabels:
      app: cdi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cdi-controller
    spec:
      serviceAccountName: cdi-sa
      containers:
      - name: cdi-controller
        image: {{ repo_tag }}/cdi-controller:v{{ release_tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: OWN_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cdi.io: ""
  name: datavolumes.cdi.io
spec:
  group: cdi.io
  names:
    kind: DataVolume
    plural: datavolumes
    shortNames:
    - dv
    - dvs
    singular: datavolume
  scope: Namespaced
  version: v1alpha1